source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'SnapKit', '~> 0.15.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 3.0'

platform :ios, '8.0'
use_frameworks!
pod 'SDWebImage', '~>3.7'

platform :ios, '8.0'
use_frameworks!
pod 'ObjectMapper', '~> 1.1'