# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HDCP' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HDCP

  target 'HDCPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HDCPUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
    pod 'ObjectMapper', '~> 3.5'
    pod 'ShareSDK3','3.5.2'
    pod 'MOBFoundation'
    pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
    pod 'ShareSDK3/ShareSDKPlatforms/QQ'
    pod 'Kingfisher'
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'Alamofire'
    pod 'SnapKit', '~> 4.0.0'
    target 'hdcpwidget' do
        pod 'Alamofire'
        pod 'SnapKit', '~> 4.0.0'
        pod 'ObjectMapper', '~> 3.5'
        pod 'Kingfisher'
    end
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end
